# Generated by Django 3.2.7 on 2021-09-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XRayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='uploads/x-ray', verbose_name='تصویر x-ray')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
            ],
            options={
                'verbose_name': 'xrayimage',
                'verbose_name_plural': 'xrayimages',
            },
        ),
    ]
